### ISSUE TITLE
错别字报告

### ISSUE THREAD

**Issue by shaolonger** [yunnysunny/nodebook#1]
3 Node基础/代码 3.2.2 b.js：
“模块话”应为“模块化”。

**Comment by yunnysunny** [comment]
谢谢指正

**Comment by shaolonger** [comment]
9 Node.js 最佳实践/代码 9.2.1 监听未捕获异常：
“这是由于如果如果不这么做的话”重复。

**Comment by shaolonger** [comment]
9 Node.js 最佳实践/9.4 使用docker：
“所以说有了docker，我们在也用担心在本地跑的好好的，结果一到服务器就出错的问题了。”
=>应该是“我们再也不用”。

**Comment by shaolonger** [comment]
10 Node.js 的 c++ 扩展：
“因为一旦你的这个这个计算服务稍微一上规模”
=>“这个”重复了。

**Comment by yunnysunny** [comment]
上面说的问题，已经修复
