### ISSUE TITLE
无法访问 Error 1001

### ISSUE THREAD

**Issue by c-z-chen** [yunnysunny/nodebook#6]
What happened?

You've requested a page on a website (nodebook.whyun.com) that is on the Cloudflare network. Cloudflare is currently unable to resolve your requested domain (nodebook.whyun.com). There are two potential causes of this:

Most likely: if the owner just signed up for Cloudflare it can take a few minutes for the website's information to be distributed to our global network.

Less likely: something is wrong with this site's configuration. Usually this happens when accounts have been signed up with a partner organization (e.g., a hosting provider) and the provider's DNS fails.

**Comment by yunnysunny** [comment]
Fixed. Thanks very much.
