### ISSUE TITLE
EZM 的部署方便在官方语雀文档同步一份吗

### ISSUE THREAD

**Issue by hyj1991** [yunnysunny/nodebook#9]
目前由于未经作者授权，暂时是添加了跳转链接，如果可以同步的话，跳转链接会使用原文链接引用的方式放到最顶部

![image](https://github.com/yunnysunny/nodebook/assets/19908330/88f0d644-d5ea-413f-a262-6858d08b9792)

**Comment by yunnysunny** [comment]
可以的
